DROP TABLE IF EXISTS CANCION;

CREATE TABLE  "CANCION" (
    "ID" NUMBER NOT NULL PRIMARY KEY,
	"NOMBRE" VARCHAR2(100) NOT NULL,
	"PLAYLIST" VARCHAR2(100) NOT NULL,
	"ARTISTA" VARCHAR2(100),
	"ALBUM" VARCHAR2(100),
	"LONGITUD" NUMBER(6)

);

